#!/bin/sh

banner() {

    echo "                    ___           ___           ___   "
    echo "     _____         /\  \         /\  \         /\  \  "
    echo "    /::\  \       /::\  \       /::\  \       /::\  \ "
    echo "   /:/\:\  \     /:/\:\__\     /:/\:\  \     /:/\:\__\ "
    echo "  /:/  \:\__\   /:/ /:/  /    /:/  \:\  \   /:/ /:/  / "
    echo " /:/__/ \:|__| /:/_/:/__/___ /:/__/ \:\__\ /:/_/:/  /  "
    echo " \:\  \ /:/  / \:\/:::::/  / \:\  \ /:/  / \:\/:/  /   "
    echo "  \:\  /:/  /   \::/~~/~~~~   \:\  /:/  /   \::/__/    "
    echo "   \:\/:/  /     \:\~~\        \:\/:/  /     \:\  \    "
    echo "    \::/  /       \:\__\        \::/  /       \:\__\   "
    echo "     \/__/         \/__/         \/__/         \/__/   "
    echo " "
    echo " "
    echo " "
    echo "     Distribued Reliable Operations Platform           "
    echo " "
    echo " "
    echo " "



}


DROP_HOME="$(dirname $(realpath $0))/../"
HOSTNAME=`env hostname -f`

# DROP_NAME=drop@${HOSTNAME}
DROP_NAME=drop@127.0.0.1


DROP_COOKIE=mesh1
DROP_LOG_DIR=/tmp
DROP_VAR_DIR=/var/lib/drop
ERL_MAX_ETS_TABLES=50000
DROP_IO_THREAD_POOL_SIZE=128
ERL_MAX_PROC=1048576
ERL_MAX_PORTS=65536
ERL_MAX_ATOMS=5000000
ERL_DBUFFER_SIZE=32000
DROP_LOGGER_MF_BYTES=10485760
DROP_LOGGER_MF_FILES=10
HEART_BEAT_TIMEOUT=30
HEART_COMMAND="${DROP_HOME}/scripts/drop"

DROP_EBIN_ROOT="${DROP_HOME}/ebin ${DROP_HOME}/apps/*/ebin "
ERL_CRASH_DUMP="${DROP_LOG_DIR}/erl_crash.dump"
NOTIFY_SOCKET=

setenv() {
    echo "setenv.."

    ulimit -n 1000000

    sysctl -w vm.swappiness=10
    sysctl -w vm.vfs_cache_pressure=10000
    # sysctl -w vm.dirty_ratio=1
    # sysctl -w vm.dirty_background_ratio=1
    # sysctl -w vm.dirty_writeback_centisecs=250
    # sysctl -w vm.dirty_expire_centisecs=3000
    # sysctl -w kernel.panic=10
    sysctl -w fs.file-max=1000000
    sysctl -w net.core.netdev_max_backlog=10000
    sysctl -w net.core.somaxconn=262144
    sysctl -w net.ipv4.tcp_syncookies=1
    sysctl -w net.ipv4.tcp_max_syn_backlog=262144
    sysctl -w net.ipv4.tcp_max_tw_buckets=720000
    sysctl -w net.ipv4.tcp_tw_recycle=1
    sysctl -w net.ipv4.tcp_timestamps=1
    sysctl -w net.ipv4.tcp_tw_reuse=1
    sysctl -w net.ipv4.tcp_fin_timeout=30
    sysctl -w net.ipv4.tcp_keepalive_time=1800
    sysctl -w net.ipv4.tcp_keepalive_probes=7
    sysctl -w net.ipv4.tcp_keepalive_intvl=30
    sysctl -w net.core.wmem_max=33554432
    sysctl -w net.core.rmem_max=33554432
    sysctl -w net.core.rmem_default=8388608
    sysctl -w net.core.wmem_default=4194394
    sysctl -w net.ipv4.tcp_rmem="4096 8388608 16777216"
    sysctl -w net.ipv4.tcp_wmem="4096 4194394 16777216"

    sysctl -p

}





help() {

    banner

    echo "start - start drop"
    echo "stop  - stop drop"
    echo "remsh - remote shell"

}


remsh() {

    exec erl \
        -setcookie ${DROP_COOKIE} \
        -remsh ${DROP_NAME} \
        -hidden \
        -connect_all false \
        -sname remsh
}



stop() {

    exec erl \
        -noshell \
        -hidden \
        -connect_all false \
        -sname temp_control \
        -setcookie ${DROP_COOKIE} \
        -eval "rpc:call('${DROP_NAME}', init, stop, [])" -s init stop

}



start() {

    banner
    # setenv

    if [ ! -d ${DROP_LOG_DIR} ]; then
            mkdir -p "${DROP_LOG_DIR}"
    fi
    if [ ! -d ${DROP_VAR_DIR} ]; then
            mkdir -p "${DROP_VAR_DIR}"
    fi

    chmod -R a+rw ${DROP_VAR_DIR}
    cd ${DROP_HOME}

    exec erl \
        -name ${DROP_NAME} \
        -setcookie ${DROP_COOKIE} \
        +K true \
        +A ${DROP_IO_THREAD_POOL_SIZE} \
        +W w \
        +P ${ERL_MAX_PROC} \
        +Q ${ERL_MAX_PORTS} \
        +t ${ERL_MAX_ATOMS} \
        +e ${ERL_MAX_ETS_TABLES} \
        +stbt s \
        +scl true \
        +zdbbl ${ERL_DBUFFER_SIZE} \
        -boot start_sasl \
        -sasl errlog_type error \
        -sasl sasl_error_logger false \
        -sasl error_logger_mf_dir \"${DROP_LOG_DIR}\" \
        -sasl error_logger_mf_maxbytes ${DROP_LOGGER_MF_BYTES} \
        -sasl error_logger_mf_maxfiles ${DROP_LOGGER_MF_FILES} \
        -kernel start_pg2 true \
        -pa ${DROP_EBIN_ROOT} \
        -env DROP_HOME ${DROP_HOME} \
        -env DROP_VAR_DIR ${DROP_VAR_DIR} \
        -env DROP_LOG_DIR ${DROP_LOG_DIR} \
        -s main

        #-noinput
        #-heart \
        #-env HEART_BEAT_TIMEOUT ${HEART_BEAT_TIMEOUT} \
        #-env HEART_COMMAND ${HEART_COMMAND} \
 
}

if [ $# -eq 0 ]
  then
      help
  else
      if [ $1 = "start" ]; then
          start
      elif [ $1 = "stop" ]; then
          stop
      elif [ $1 = "remsh" ]; then
          remsh
      fi
fi


