#!/bin/sh


realpath() {
    local path=$1

    if [ -d "$path" ]; then
        cd "$path" && pwd
    elif [ -f "$path" ]; then
        cd "$(dirname "$path")" && echo $(pwd)/$(basename "$path")
    else
        echo "$path"
    fi
}


DROP_HOME="$(realpath "../")"
HOSTNAME=`env hostname -f`
DROP_NAME=drop@${HOSTNAME}
DROP_COOKIE=123

DROP_EBIN_ROOT="${DROP_HOME}/ebin "\
               "${DROP_HOME}/apps/node_watch/ebin "\
               "${DROP_HOME}/apps/node_scheduler/ebin "

DROP_LOG_DIR=/tmp
DROP_VAR_DIR=/var/lib/drop/

ERL_CRASH_DUMP="${DROP_LOG_DIR}/erl_crash.dump"

ERL_MAX_ETS_TABLES=50000
DROP_IO_THREAD_POOL_SIZE=128

NOTIFY_SOCKET=


if [ ! -d ${DROP_LOG_DIR} ]; then
        mkdir -p "${DROP_LOG_DIR}"
fi
if [ ! -d ${DROP_VAR_DIR} ]; then
        mkdir -p "${DROP_VAR_DIR}"
fi

exec erl \
	-name ${DROP_NAME} \
	-setcookie ${DROP_COOKIE} \
    +K true \
    +A ${DROP_IO_THREAD_POOL_SIZE} \
    +W w \
    +P 1048576 \
    +Q 65536 \
    +t 5000000 \
    +stbt db \
    +zdbbl 1024 \
	-boot start_sasl \
	-sasl errlog_type error \
	-sasl sasl_error_logger false \
	-sasl error_logger_mf_dir \"${DROP_LOG_DIR}\" \
	-sasl error_logger_mf_maxbytes 10485760 \
	-sasl error_logger_mf_maxfiles 10 \
	-kernel start_pg2 true \
	-pa ${DROP_EBIN_ROOT} \
    -noinput \
   	-s main

