#!/usr/bin/python

#
# Collector node worker
#

import sys
import time
import json

# API


def log(m):
    sys.stderr.write("{}: {}\n".format(time.time(), m))


def send(m):
    sys.stdout.write("{}\n".format(m))
    sys.stdout.flush()


# Process - actor
#  line - recieve message from world
#  send - send message to world
#  log  -  logging anything


NodeInfo = {}


def main():

    while 1:
        line = sys.stdin.readline()
        if not line:
            break

        log("start working..")
        log("get message: " + line)

        data = json.loads(line)

        NodeInfo[data["node"]] = data

        send(NodeInfo)
        log("message send: {}".format(NodeInfo))


if __name__ == "__main__":
    main()
